- name: nginx Install and RUN
  hosts: web
  become: yes #takes sudo access
  tasks:
  - name: nginx Install
    ansible.builtin.package:
      name: nginx
      state: present


- name: run nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes