- name: Variables to Print
  hosts: web
  vars:
    COURSE: DevOps
    DURATION: 100 HRS
    LEARNING: SELF
  tasks:
  - name: Print the Information
    ansible.builtin.debug:
      msg: "Hi, I am learning DevOps with AWS"
      