- name: Variables from Prompt
  hosts: web
  vars:
    COURSE: DevOps from PLAY LEVEL
    DURATION: 100 HRS
    LEARNING: SELF
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course
    private: false # Information Will be Shown In TERMINAL
  - name: DURATION
    prompt: Please enter the duration
    private: false # Information Will be Shown In TERMINAL
  - name: LEARNING
    prompt: Enter Training Mode
    private: false # Information Will be Shown In TERMINAL
  tasks:
  - name: Print the course Information
  vars:
      COURSE: DevOps from TASK LEVEL
      DURATION: 100 HRS
      LEARNING: SELF
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Learning is: {{LEARNING}}"