- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: Please enter the number
    private: false # Information Will be Shown In TERMINAL
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number is {{ number }} is less than 10"
    when: number | int < 10 #Conditional Expression


  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number is {{ number }} greater than or equal 10"
    when: number | int >= 10 #Conditional Expression