- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: Print the Packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - postfix
    - nagios