- name: Demo on Filters/Functions
  hosts: web
  tasks:
  - name: Print the Default Values
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('Ansible')}}"

  - name: convert to upper
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"


  - name: convert to lower
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"


  - name: Print the Unique Numbers
    vars:
      numbers: [1,2,3,41,2,33,7,991,12,3]
    ansible.builtin.debug:
      msg: "{{ numbers | unique}}"

  - name: get the min and max
    vars:
      numbers: [1,2,3,41,2,33,7,991,12,3]
    ansible.builtin.debug:
      msg: " Min: {{ numbers | min }}, Max: {{ numbers | max }}"

