- name: Demo on Filters/Functions
  hosts: web
  tasks:
  - name: Print the Default Values
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('Ansible')}}"

  - name: convert to upper
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"


  - name: convert to lower
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"